#!/bin/bash

# install dependencies
brew install fzf tmux vim curl

# install zgenom
git clone https://github.com/jandamm/zgenom.git ~/.zgenom

# install tmux plugin manager
mkdir -p ~/.tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
